version: "3"

services:
  web:
      build:
        context: .
        dockerfile: ./docker/nginx/Dockerfile
      ports:
          - "80:80"
      links:
          - php
  php:
      image: php:7.3.5-fpm-alpine
      volumes:
          - ./:/app
